# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pbft_pb2 as pbft__pb2


class PbftServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendPreprepare = channel.unary_unary(
        '/PbftService/SendPreprepare',
        request_serializer=pbft__pb2.PbftPreprepare.SerializeToString,
        response_deserializer=pbft__pb2.Empty.FromString,
        )
    self.SendPrepare = channel.unary_unary(
        '/PbftService/SendPrepare',
        request_serializer=pbft__pb2.PbftPrepare.SerializeToString,
        response_deserializer=pbft__pb2.Empty.FromString,
        )
    self.SendCommit = channel.unary_unary(
        '/PbftService/SendCommit',
        request_serializer=pbft__pb2.PbftCommit.SerializeToString,
        response_deserializer=pbft__pb2.Empty.FromString,
        )


class PbftServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendPreprepare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendPrepare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendCommit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PbftServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendPreprepare': grpc.unary_unary_rpc_method_handler(
          servicer.SendPreprepare,
          request_deserializer=pbft__pb2.PbftPreprepare.FromString,
          response_serializer=pbft__pb2.Empty.SerializeToString,
      ),
      'SendPrepare': grpc.unary_unary_rpc_method_handler(
          servicer.SendPrepare,
          request_deserializer=pbft__pb2.PbftPrepare.FromString,
          response_serializer=pbft__pb2.Empty.SerializeToString,
      ),
      'SendCommit': grpc.unary_unary_rpc_method_handler(
          servicer.SendCommit,
          request_deserializer=pbft__pb2.PbftCommit.FromString,
          response_serializer=pbft__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PbftService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
