# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pbft.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pbft.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\npbft.proto\"n\n\x0ePbftPreprepare\x12\n\n\x02sn\x18\x01 \x01(\x05\x12\x0c\n\x04view\x18\x02 \x01(\x05\x12\x0e\n\x06leader\x18\x03 \x01(\x05\x12\x15\n\x05\x62\x61tch\x18\x04 \x01(\x0b\x32\x06.Batch\x12\x0f\n\x07\x61\x62orted\x18\x05 \x01(\x08\x12\n\n\x02ts\x18\x06 \x01(\x03\"7\n\x0bPbftPrepare\x12\n\n\x02sn\x18\x01 \x01(\x05\x12\x0c\n\x04view\x18\x02 \x01(\x05\x12\x0e\n\x06\x64igest\x18\x03 \x01(\x0c\"B\n\nPbftCommit\x12\n\n\x02sn\x18\x01 \x01(\x05\x12\x0c\n\x04view\x18\x02 \x01(\x05\x12\x0e\n\x06\x64igest\x18\x03 \x01(\x0c\x12\n\n\x02ts\x18\x04 \x01(\x03\"\x15\n\x05\x42\x61tch\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x80\x01\n\x0bPbftService\x12)\n\x0eSendPreprepare\x12\x0f.PbftPreprepare\x1a\x06.Empty\x12#\n\x0bSendPrepare\x12\x0c.PbftPrepare\x1a\x06.Empty\x12!\n\nSendCommit\x12\x0b.PbftCommit\x1a\x06.Emptyb\x06proto3')
)




_PBFTPREPREPARE = _descriptor.Descriptor(
  name='PbftPreprepare',
  full_name='PbftPreprepare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn', full_name='PbftPreprepare.sn', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='view', full_name='PbftPreprepare.view', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leader', full_name='PbftPreprepare.leader', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch', full_name='PbftPreprepare.batch', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aborted', full_name='PbftPreprepare.aborted', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='PbftPreprepare.ts', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=124,
)


_PBFTPREPARE = _descriptor.Descriptor(
  name='PbftPrepare',
  full_name='PbftPrepare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn', full_name='PbftPrepare.sn', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='view', full_name='PbftPrepare.view', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digest', full_name='PbftPrepare.digest', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=181,
)


_PBFTCOMMIT = _descriptor.Descriptor(
  name='PbftCommit',
  full_name='PbftCommit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn', full_name='PbftCommit.sn', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='view', full_name='PbftCommit.view', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digest', full_name='PbftCommit.digest', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='PbftCommit.ts', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=249,
)


_BATCH = _descriptor.Descriptor(
  name='Batch',
  full_name='Batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Batch.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=272,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=281,
)

_PBFTPREPREPARE.fields_by_name['batch'].message_type = _BATCH
DESCRIPTOR.message_types_by_name['PbftPreprepare'] = _PBFTPREPREPARE
DESCRIPTOR.message_types_by_name['PbftPrepare'] = _PBFTPREPARE
DESCRIPTOR.message_types_by_name['PbftCommit'] = _PBFTCOMMIT
DESCRIPTOR.message_types_by_name['Batch'] = _BATCH
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbftPreprepare = _reflection.GeneratedProtocolMessageType('PbftPreprepare', (_message.Message,), dict(
  DESCRIPTOR = _PBFTPREPREPARE,
  __module__ = 'pbft_pb2'
  # @@protoc_insertion_point(class_scope:PbftPreprepare)
  ))
_sym_db.RegisterMessage(PbftPreprepare)

PbftPrepare = _reflection.GeneratedProtocolMessageType('PbftPrepare', (_message.Message,), dict(
  DESCRIPTOR = _PBFTPREPARE,
  __module__ = 'pbft_pb2'
  # @@protoc_insertion_point(class_scope:PbftPrepare)
  ))
_sym_db.RegisterMessage(PbftPrepare)

PbftCommit = _reflection.GeneratedProtocolMessageType('PbftCommit', (_message.Message,), dict(
  DESCRIPTOR = _PBFTCOMMIT,
  __module__ = 'pbft_pb2'
  # @@protoc_insertion_point(class_scope:PbftCommit)
  ))
_sym_db.RegisterMessage(PbftCommit)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), dict(
  DESCRIPTOR = _BATCH,
  __module__ = 'pbft_pb2'
  # @@protoc_insertion_point(class_scope:Batch)
  ))
_sym_db.RegisterMessage(Batch)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'pbft_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)



_PBFTSERVICE = _descriptor.ServiceDescriptor(
  name='PbftService',
  full_name='PbftService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=284,
  serialized_end=412,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendPreprepare',
    full_name='PbftService.SendPreprepare',
    index=0,
    containing_service=None,
    input_type=_PBFTPREPREPARE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendPrepare',
    full_name='PbftService.SendPrepare',
    index=1,
    containing_service=None,
    input_type=_PBFTPREPARE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendCommit',
    full_name='PbftService.SendCommit',
    index=2,
    containing_service=None,
    input_type=_PBFTCOMMIT,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PBFTSERVICE)

DESCRIPTOR.services_by_name['PbftService'] = _PBFTSERVICE

# @@protoc_insertion_point(module_scope)
